# Hola! 👋

Mi nombre es David y soy Desarrollador Web Full Stack! Cuento con un Título de grado de "Licenciado en Administración" lo cual es gran parte de mi forma de ver el mundo, pero la programación se ganó mi corazón, mi atención y prácticamente todo mi tiempo. Siempre disfruté los desafíos, la resolución de problemas y el aprendizaje continuo. Haber encontrado reunir todo esto y mucho más en un sólo ámbito me apasiona como no me había pasado antes.
Mis planes son continuar aprendiendo y mejorando mis habilidades técnicas y blandas.

Estoy utilizando principalmente Javascript, React, Redux, NodeJS, postgreSQL. Afianzandome en estas tecnologías pero con intenciones de sumar Typescript a mis proyectos en el corto plazo.

¡No dudes en contactarme, estoy disponible!
<!--
**etchepared/etchepared** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
